name: DEPLOY TO STAGING

on:
    pull_request:
        types : [closed]
        branches:
            - master

jobs:
    aws-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: master
            - uses: actions/setup-node@v1
              with:
                node-version: '14'
            - run: npm install
            - run: npm run build
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@v2.1.1
              env:
                    SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                    ARGS: "-rltgoDzvO --delete"
                    SOURCE: "dist/"
                    REMOTE_HOST: "ec2-13-127-147-193.ap-south-1.compute.amazonaws.com"
                    REMOTE_USER: ubuntu
                    TARGET: "/home/ubuntu/react/deploy/"
